/** @jsxImportSource @emotion/react */
import Head from 'next/head'
import {
  useQuery,
} from "react-query";
import { getAllArticles } from '../api/articles.api';
import { IndexArticleList, IndexH1, IndexMain } from '../styles/index.emotion';
import { displayArticleTitles } from '../utils/index.utils';

export default function Home(props) {
  const { data } = useQuery('allArticles', getAllArticles, { initialData: props.allArticles })

  return (
    <div>
      <Head>
        <title>Test NextJs v12</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={IndexMain}>
        <h1 css={IndexH1}>
          Welcome to <a href="https://nextjs.org">Next.js ^v12!</a>
        </h1>

        <ul css={IndexArticleList}>
          {displayArticleTitles(data?.allArticles?.edges)}
        </ul>
      </main>
    </div>
  )
}

export async function getStaticProps(context) {
  const allArticles = await getAllArticles()
  return{
    props:{ allArticles }
  }
}
