/** @jsxImportSource @emotion/react */
import Head from 'next/head'
// import {
//   useQuery,
// } from "react-query";
// import { getAllArticles } from '../api/articles.api';
import { IndexH1, IndexMain } from '../styles/index.emotion';

export default function Home( props: Home ) {
  return (
    <div>
      <Head>
        <title>Test NextJs v12</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main css={IndexMain}>
        <h1 css={IndexH1}>
          Welcome to <a href="https://nextjs.org">Next.js ^v12!</a>
        </h1>
      </main>
    </div>
  )
}

type Home = {
  test: string
  //// key is the name of the prop and
// value is the PropType
}

// export async function getStaticProps(context) {
//   const allArticles = await getAllArticles()
//   return{
//     props:{ allArticles }
//   }
// }
